### ISSUE TITLE
Compilation fails with -O0 and -Os.

### ISSUE THREAD

**Issue by Saribro** [travisdowns/uarch-bench#16]
Compiling with -O1/-O2/-O3 is fine, -O0/-Os result in the following:
> g++ -g -O0 -march=native -DGIT_VERSION=\"4fb3130-dirty\" -c -std=c++11 -o main.o main.cpp
nasm -w+all -f elf64 -l x86_methods.list x86_methods.asm
g++ -g -O0 -march=native -DGIT_VERSION=\"4fb3130-dirty\" main.o x86_methods.o -o uarch-bench
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &load16_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &load32_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &load64_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &load128_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &load256_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &store16_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &store32_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &store64_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &store128_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
main.o: In function 'std::shared_ptr<LoadStoreGroup> LoadStoreGroup::make<ClockTimerT<std::chrono::_V2::system_clock>, &store256_any>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int)':
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_COLS'
/home/swinnenb/uarch-bench/main.cpp:338: undefined reference to 'LoadStoreGroup::DEFAULT_ROWS'
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'uarch-bench' failed
make: *** [uarch-bench] Error 1

GCC version:

> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

System:
> Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by travisdowns** [comment]
Yeah I encountered this locally also. Will fix shortly.

**Comment by travisdowns** [comment]
Fixed in master.
