### ISSUE TITLE
libpfc isn't building on Arch Linux

### ISSUE THREAD

**Issue by travisdowns** [travisdowns/uarch-bench#25]
Per Peter on issue #24:

I'm having trouble getting libpfc built on Arch Linux. I cded into uarch-bench/libpfc and did a make clean, then make:

```
rm -rf kmod.build
cp -r kmod kmod.build
cd kmod.build && make MAKEFLAGS=
make[1]: Entering directory '/usr/local/src/uarch-bench/libpfc/kmod.build'
make -C /lib/modules/4.12.8-2-ARCH/build M=/usr/local/src/uarch-bench/libpfc/kmod.build modules
make[2]: Entering directory '/usr/lib/modules/4.12.8-2-ARCH/build'
make[2]: *** No rule to make target 'modules'.  Stop.
make[2]: Leaving directory '/usr/lib/modules/4.12.8-2-ARCH/build'
make[1]: *** [Makefile:5: all] Error 2
make[1]: Leaving directory '/usr/local/src/uarch-bench/libpfc/kmod.build'
make: *** [Makefile:30: pfc.ko] Error 2
```

I don't see how the make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules is supposed to work, because there's no modules anywhere in libpfc or in /usr/lib/modules/4.12.8-2-ARCH/, just modules.*. Same on my Ubuntu 15.04 machine using a distro kernel. (I keep putting off updating it until I make a grand plan to put it on an SSD or something...)

And the Makefile doesn't define this target.

**Comment by travisdowns** [comment]
As far as I know, this is the "standard" way to build a kernel module. There should be a directory called `build` in `/usr/lib/modules/4.12.8-2-ARCH/`, and then `make` is invoked there with the `modules` target (which is a standard target defined by the kernel module build infra, it doesn't come from this project).

What does your `/lib/modules/` tree look like? You mention `/usr/lib/modules/4.12.8-2-ARCH/` but the build is trying to use `/lib/modules/4.12.8-2-ARCH/build` (no `/usr/*`).

Here's some info from my Ubuntu 16.04 system:

```
ls /lib/modules/
4.10.0-33-generic  4.10.0-35-generic  4.10.0-37-generic  4.4.0-93-generic  4.4.0-96-generic  4.4.0-97-generic
ls -l /lib/modules/4.10.0-37-generic/build
lrwxrwxrwx 1 root root 40 Oct  6 18:40 /lib/modules/4.10.0-37-generic/build -> /usr/src/linux-headers-4.10.0-37-generic
```

Here's [info](https://wiki.archlinux.org/index.php/Compile_kernel_module) on building kernel modules on Arch. It seems to follow the pattern above. Check that you have the dependencies installed, like `base-devel` and `linux-headers`?

**Comment by travisdowns** [comment]
Actually after taking a better look at the link I gave above, it seems you need to do a bit of work to get the source needed to build the kernel module. See the part under "Source configuration" [here](https://wiki.archlinux.org/index.php/Compile_kernel_module). Once you do that, it should work.

**Comment by pcordes** [comment]
Silly me, I didn't have `linux-headers` installed.  Probably I don't have that on the Ubuntu machine either.  I guess I was expecting the error message to be something different if that was the problem.

On Arch, `/lib` is a symlink to `/usr/lib` by default.  You could change that if you wanted to have `/usr` not on the root FS.  That's why `pwd` finds /usr/lib/...

```
$ ll /usr/lib/modules/4.12.8-2-ARCH/build/
total 23M
-rw-r--r-- 1 root root 29M Aug 18 11:09 vmlinux
```

So yes there is a `build` directory, even without `linux-headers` installed.

Arch is a rolling-release distro, so headers for the kernel I'm running aren't still available in the main repos.  I'll have to remember to install kernel headers next time I'm ready to reboot and upgrade my kernel (+ the rest of the system).

**Comment by travisdowns** [comment]
Closing this as @pcordes confirmed above the issue was missing kernel module build environment on the local box.
