### ISSUE TITLE
uarch-bench not building due to missing libpfm4

### ISSUE THREAD

**Issue by travisdowns** [travisdowns/uarch-bench#38]
Change 5b6777a30778fea47af67d9ee9797d78fea4a9f4 removed the libpfc `.tar` and replaced it with a submodule pointing to the sourceforce git view for that library.

After this change, `uarch-bench` isn't building because the submodule doesn't seem to exist: a fresh `git clone --recursive` brings in the other three submodules but not `libpfm4` and `git submodule status` and friends don't seem to know about it.

Similar issue [described here](https://stackoverflow.com/q/3336995/149138).

**Comment by travisdowns** [comment]
@nemequ

**Comment by travisdowns** [comment]
Fixed in 7c18693.

**Comment by nemequ** [comment]
Interesting. I'm pretty sure it wasn't showing up as an unstaged stauts in `git status`, and `git submodule add …` is how I added it… I'd love to know how that happened, but I'm not sure what I can do to check at this point :(

Anyways, sorry about the issue.

**Comment by travisdowns** [comment]
@nemequ - no worries, it's not a problem (it's anyways my fault for not testing it locally before mering and not having any CI set up).

Based on my experience, `git submodule add` and also `git add .` is not enough, you need an explicit `git add <submodule-name>` to get the submodule commit? At least that's true for updates, not sure about the initial add.

Based on [this change](https://github.com/nemequ/uarch-bench/commit/5b6777a30778fea47af67d9ee9797d78fea4a9f4) it was already not present when you pushed to git, you could always check if it's present for you locally (i.e., what does `git submodule status` or `git config --list` report).

**Comment by nemequ** [comment]
I never use `git add .`, but the module should show up in `git status` as having unstaged content, and I'm usually pretty careful to check that before committing anything.

I thought about adding CI, but AFAIK there isn't really a good way to test since uarch-bench wants root, and Travis is moving away from allowing root… if you want I could throw together a quick PR which just builds uarch-bench.

**Comment by travisdowns** [comment]
@nemequ - I mean the most interesting way to run `uarch-bench` is using root, but `uarch-bench` definitely doesn't need root (the README has a section about what you lose if you don't run as root).

For the purposes of CI, running as non-root will be totally fine I think: it's mostly initially about testing the build, and runtime which pretty much runs identically with root and not. Furthermore, running as non-root is a good testcase to make sure we don't break that flow!

I'm totally happy with any help you are willing to do add CI. Just a build, and then an execution of ./uarch-bench as non-root would be a big step.

**Comment by travisdowns** [comment]
@nemequ - let's continue any CI-specific discussion on #41 .
