### ISSUE TITLE
Add the ability to restrict some benchmarks to CPUs with certain ISA extensions

### ISSUE THREAD

**Issue by travisdowns** [travisdowns/uarch-bench#56]
For example, a benchmark could be tagged with AVX2 if it needs AVX2 to run. This is a lot better than simply crashing when the user runs such a benchmark on an incompatible machine.

Among other things this prevents us from running with `--test-name=*` on the CI server since it doesn't always have AVX2 and crashes on some test that needs it.

**Comment by nemequ** [comment]
It's not as well tested as I'd like, but https://github.com/nemequ/portable-snippets/tree/master/cpu may help.
