### ISSUE TITLE
build failed with error: struct perf_event_mmap_page’ has no member named ‘cap_user_rdpmc

### ISSUE THREAD

**Issue by dongxiao92** [travisdowns/uarch-bench#71]
Hey, I just follow the instructions on the page. But the building stage encountered error:

> g++ -MMD -Wall  -g -O2 -DGIT_VERSION=\"b6d37f9\" -DUSE_LIBPFC=1 -DUSE_BACKWARD_CPP=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DUSE_PERF_TIMER=1 -Iportable-snippets -Iboost_1_70_0  -c -std=c++11 -o perf-tim=er.o perf-timer.cpp
> perf-timer.cpp: In function ‘void print_caps(std::ostream&, const rdpmc_ctx&)’:perf-timer.cpp:163:31: error: ‘struct perf_event_mmap_page’ has no member named ‘cap_user_rdpmc’
>              " R:" << ctx.buf->cap_user_rdpmc <<                               ^perf-timer.cpp:164:32: error: ‘struct perf_event_mmap_page’ has no member named ‘cap_user_time’
>              " UT:" << ctx.buf->cap_user_time <<                                ^perf-timer.cpp:165:32: error: ‘struct perf_event_mmap_page’ has no member named ‘cap_user_time_zero’
>              " ZT:" << ctx.buf->cap_user_time_zero <<
>                                 ^
> make: *** [perf-timer.o] Error 1

The environment information is listed below.

gcc: 4.8.5
OS: CentOS6

**Comment by dongxiao92** [comment]
After setting **USE_PERF_TIMER** to 0, the above issue dose not show up, but new issue comes:

> ++ -MMD -Wall  -g -O2 -DGIT_VERSION=\"b6d37f9-dirty\" -DUSE_LIBPFC=1 -DUSE_BACKWARD_CPP=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DUSE_PERF_TIMER=0 -Iportable-snippets -Iboost_1_70_0  -c -std=c++11 -o timers.o timers.cpp
> timers.cpp: In function ‘void printClockOverheads(std::ostream&)’:
> timers.cpp:133:32: error: ‘CLOCK_BOOTTIME’ was not declared in this scope
>      PRINT_CLOCK(GettimeAdapter<CLOCK_BOOTTIME>);
>                                 ^
> timers.cpp:121:43: note: in definition of macro ‘PRINT_CLOCK’
>  #define PRINT_CLOCK(clock) printOneClock< clock >(out, #clock);
>                                            ^
> timers.cpp:133:46: error: template argument 1 is invalid
>      PRINT_CLOCK(GettimeAdapter<CLOCK_BOOTTIME>);
>                                               ^
> timers.cpp:121:43: note: in definition of macro ‘PRINT_CLOCK’
>  #define PRINT_CLOCK(clock) printOneClock< clock >(out, #clock);
>                                            ^
> timers.cpp:121:62: error: no matching function for call to ‘printOneClock(std::ostream&, const char [31])’
>  #define PRINT_CLOCK(clock) printOneClock< clock >(out, #clock);
>                                                               ^
> timers.cpp:133:5: note: in expansion of macro ‘PRINT_CLOCK’
>      PRINT_CLOCK(GettimeAdapter<CLOCK_BOOTTIME>);
>      ^
> timers.cpp:121:62: note: candidate is:
>  #define PRINT_CLOCK(clock) printOneClock< clock >(out, #clock);
>                                                               ^
> timers.cpp:133:5: note: in expansion of macro ‘PRINT_CLOCK’
>      PRINT_CLOCK(GettimeAdapter<CLOCK_BOOTTIME>);
>      ^
> timers.cpp:107:6: note: template<class CLOCK> void printOneClock(std::ostream&, const char*)
>  void printOneClock(std::ostream& out, const char* name) {
>       ^
> timers.cpp:107:6: note:   template argument deduction/substitution failed:
> timers.cpp:121:62: error: template argument 1 is invalid
>  #define PRINT_CLOCK(clock) printOneClock< clock >(out, #clock);
>                                                               ^
> timers.cpp:133:5: note: in expansion of macro ‘PRINT_CLOCK’
>      PRINT_CLOCK(GettimeAdapter<CLOCK_BOOTTIME>);
>      ^
> make: *** [timers.o] Error 1
> make: *** Waiting for unfinished jobs....

**Comment by travisdowns** [comment]
Thanks for the report @dongxiao92 .

Can you do me a favor and tell me your full kernel version as reported by `uname -a`?

I think there are actually two separate issues here. One is that uarch-bench doesn't build on older kernels due to missing `cap_user_time[_zero]`.

The other issue is the one you had building with `USE_PERF_TIMER=0`, I'll create another issue for that.

**Comment by travisdowns** [comment]
@dongxiao92 - both issues should be fixed now, but can you pull and try to build on your system to verify?

**Comment by dongxiao92** [comment]
Thanks for your quick reply. I pull the update and test on my machine. The new error message is:

> util.cpp: In function ‘void* new_huge_ptr(size_t)’:
> util.cpp:77:33: error: ‘MADV_HUGEPAGE’ was not declared in this scope
>      madvise(ptr, size + TWO_MB, MADV_HUGEPAGE);
>                                  ^
> make: *** [util.o] Error 1
> make: *** Waiting for unfinished jobs....

And the output of `uname -a` is:
Linux 695190 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by travisdowns** [comment]
@dongxiao92  - thanks, I'm working on fixing this. The issue is that you are on a very old kernel (2.6) so some things are missing. If you could run a `make -k` to keep making the rest of the files it might help becaue you can see more build issues and report them all at once.

**Comment by travisdowns** [comment]
@dongxiao92 - can you try newest commit 66cbe1ea7eaf9b894394a6cd0feccb7e1da2f672 ?

It has a fix for this issue.

**Comment by dongxiao92** [comment]
@travisdowns Thank you so much for quick reply. I have tried the newest commit. The new error is:

> g++ -MMD -Wall  -g -O2 -DGIT_VERSION=\"66cbe1e\" -DUSE_LIBPFC=1 -DUSE_BACKWARD_CPP=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DUSE_PERF_TIMER=1 -Iportable-snippets -Iboost_1_70_0 -DUARCH_BENCH_PORTABLE=0  -c -std=c++11 -o unit-test.o test/unit-test.cpp
> Buiding libpfc target all
> g++ -MMD -Wall  -g -O2 -DGIT_VERSION=\"66cbe1e\" -DUSE_LIBPFC=1 -DUSE_BACKWARD_CPP=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DUSE_PERF_TIMER=1 -Iportable-snippets -Iboost_1_70_0 -DUARCH_BENCH_PORTABLE=0  -c -std=c++11 -o unit-test-main.o test/unit-test-main.cpp
> make -C libpfc all
> make[1]: Entering directory `/home/dongxiao/working/uarch-bench/libpfc'
> cc -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,-soname,libpfc.so '-Wl,-rpath,$ORIGIN/' libpfc.o -o libpfc.so
> cc -Wall -Winvalid-pch -O0 -g -Iinclude -std=gnu99 -c src/pfcdemo.c -o pfcdemo.o
> src/pfcdemo.c: Assembler messages:
> src/pfcdemo.c:29: Error: suffix or operands invalid for `vpaddd'
> src/pfcdemo.c:33: Error: suffix or operands invalid for `vpaddd'
> src/pfcdemo.c:36: Error: suffix or operands invalid for `vpaddd'
> src/pfcdemo.c:37: Error: suffix or operands invalid for `vpaddd'
> src/pfcdemo.c:40: Error: suffix or operands invalid for `vpaddd'
> make[1]: *** [pfcdemo.o] Error 1

**Comment by travisdowns** [comment]
@dongxiao92  - the issue is that your gcc (actually `gas`) is too old to understand AVX-512 instructions properly.

I have committed a change to stop building the demo by default, since it isn't needed by uarch-bench.

Can you try again?

**Comment by dongxiao92** [comment]
@travisdowns - Thank you. I have tried the newest commit. The build error  now is shown below.

> /home/dongxiao/working/uarch-bench/libpfc/kmod.build/pfckmod.c:189:2: error: unknown field ‘bin_attrs’ specified in initializer
>   .bin_attrs  = (struct bin_attribute **)PFC_BIN_ATTR_GRP_LIST

**Comment by travisdowns** [comment]
@dongxiao92 you kernel is too old to support libpfc timer, but it can work without it.

Can you try:

`make clean && make USE_LIBPFC=0`

?

You can create a `local.mk` file and put `USE_LIBPFC := 0` in there.

If it fails, please run `make -k` which will show _all_ the failures so we don't have to solve them one-by-one.

**Comment by dongxiao92** [comment]
@travisdowns
I add the `USE_LIBPFC =0` flag and comlete the building with same modifications, which are listed below.
(1) link error:unrecognized command line option ‘-no-pie’
I do some goolging and find this is due to the gcc version. Old gccs do not have this option. For my gcc 4.8.5, it has an option of '-pie' to enable position independent code([https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/Link-Options.html#Link-Options]). Thus I just comment the '-no-pie' in the Makefile. Maybe the probing of the underlying compiler version is required before determining if this link option is added.
(2) undefined reference to 'clock_gettime' and 'clock_settime'
I add the '-lrt' link option.

Thank you for your help.
