### ISSUE TITLE
Build error due to outdated libpfm4

### ISSUE THREAD

**Issue by xoqolatl** [travisdowns/uarch-bench#73]
uarch-bench won't build with GCC 8.1-8.3 because of truncation error in libpfm4. This was fixed a year ago in perfmon: https://sourceforge.net/p/perfmon2/bugs/7/ but is not updated in uarch-bench yet. uarch-bench builds fine when I replace libpfm4 with latest version.

**Comment by travisdowns** [comment]
Thanks @xoqolatl - I've updated libpfm to master HEAD, can you pull and do a `submodule update` and see if it works for you?

**Comment by xoqolatl** [comment]
This has resolved the issue. Thanks!
