### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by jdetchart** [travisdowns/uarch-bench#78]
I have a compilation error on my machine (Ubuntu 16.04, i7-6700) when i run make: 
`using system nasm
USE_LIBPFC=1 USE_PERF_TIMER=1
nasm -DNASM_ENABLE_DEBUG=0 -w+all  -f elf64 x86-methods.asm
x86-methods.asm:669: error: invalid combination of opcode and operands
Makefile:132: recipe for target 'x86-methods.o' failed
make: *** [x86-methods.o] Error 1
`

https://github.com/travisdowns/uarch-bench/blob/848fa0facfd09a13217c6aafeea2634536461eae/x86-methods.asm#L669
The vpxorq should have 3 operands. If i replace the line by "vpxorq zmm16, zmm16, zmm16", compilation works fine.

**Comment by travisdowns** [comment]
Thanks, can you include the output of:

nasm --version

On your system?

**Comment by travisdowns** [comment]
Thanks @jdetchart , I'm fixing this now.

Thanks, can you include the output of:

```
nasm --version
```

On your system?

It's definitely a bug, `vpxor` should always have three arguments (you can see in the two previous functions I messed this up, too), but it seems some versions of nasm are more tolerant, curious which ones.

**Comment by jdetchart** [comment]
> Thanks @jdetchart , I'm fixing this now.
> 
> As a favor, can you include the output of:
> 
> ```
> nasm --version
> ```
> 
> ... on your system?
> 
> It's definitely a bug, `vpxor` should always have three arguments (you can see in the two previous functions I messed this up, too), but it seems some versions of nasm are more tolerant, curious which ones.

nasm -v gives me: `NASM version 2.11.08`
