### ISSUE TITLE
how can i test the performance of the snippet of assembly provided by myself

### ISSUE THREAD

**Issue by mtpony** [travisdowns/uarch-bench#88]
i want test the snippet of assembly provided by myself, but the tool seems that it can only test the buil-in benchmark, so what can i do？

**Comment by travisdowns** [comment]
Hi @jack-tan2 - you can add your test. This isn't exactly user-friendly at the moment and I haven't created a doc, but the best way is to follow an existing change that does what you want. [Here's an example](https://github.com/travisdowns/uarch-bench/commit/9690f12b73be0c1ca9f9b3e2874ac794cc01c1f6) that adds a single asm benchmark that you could use as a template. 

Let me know if you have any questions.

**Comment by travisdowns** [comment]
Hi @mtpony - I hope this worked for you, and I'm closing this issue as I don't think there's anything to track here. Feel free to open it if you have additional questions.
