### ISSUE TITLE
remove MINSIGSTKSZ usage

### ISSUE THREAD

**Issue by olafhering** [travisdowns/uarch-bench#90]
glibc 2.34 turned this macro into a function call (or did similar breakage). See ocaml/ocaml#10250 for a discussion about the issue.

tldr:
````
[  113s] test/catch.hpp:7422:58: error: call to non-'constexpr' function 'long int sysconf(int)'
[  113s]  7422 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
````

**Comment by travisdowns** [comment]
Thanks for the report @olafhering.

Looks like I need to update catch2:

https://github.com/catchorg/Catch2/issues/2178

**Comment by travisdowns** [comment]
Hi Olaf, this should be fixed, give it a shot and let me know if it works (hard to test since I don't have such a new glibc version).

**Comment by olafhering** [comment]
Thank you, [all green](https://build.opensuse.org/package/show/benchmark/uarch-bench) again.
