### ISSUE TITLE
dead link on wiki

### ISSUE THREAD

**Issue by ldoolitt** [travisdowns/uarch-bench#92]
https://github.com/travisdowns/uarch-bench/wiki/Links
Method for reverse engineering the physical-DRAM mapping describes how to determine the DRAM bank mappings by searching for bank collisions via timing.
http://asg.ict.ac.cn/baoyg/downloads/PACT12-BPM.pdf
404 not found

**Comment by ldoolitt** [comment]
I'm personally struggling to get a proper rowhammer evaluation on a Ryzen 5000 series CPU -- having trouble finding any meaningful tools that will give me a start on the DDR4 mapping step.  There's a small chance this paper will help, but I won't know until I read it.

**Comment by travisdowns** [comment]
@ldoolitt - here's the ACM link with the DOI:

https://dl.acm.org/doi/10.1145/2370816.2370869

sci-hub has the full text, or get the revised version directly from the author's github:

https://liulei-sys-inventor.github.io/files/pact140-liu-final.pdf

**Comment by travisdowns** [comment]
Link updated on wiki.
